{
  "data_path": "/projects/a5k/public/data/annealing-mix/annealing-mix_text_document",
  "vocab_file": "/projects/a5k/public/data/neox_tokenizer/tokenizer.json",
  "tokenizer_type": "HFTokenizer",
  "data_impl": "mmap",
  "use_wandb": false,
  "wandb_host": "https://api.wandb.ai",
  "wandb_project": "AISI",
  "wandb_team": "eleutherai",
  "wandb_run_name": "ga_midtraining_deep_ignorance_N_16",
  "pipe_parallel_size": 1,
  "model_parallel_size": 1,
  "launcher": "slurm",
  "deepspeed_slurm": true,
  "no_ssh_check": true,
  "train_iters": 12667,
  "lr_decay_iters": 12667,
  "distributed_backend": "nccl",
  "lr_decay_style": "cosine",
  "warmup": 0.01,
  "split": "100,0,0",
  "eval_interval": 1000,
  "eval_iters": 0,
  "eval_tasks": [
    "wmdp_bio_aisi_robust",
    "wmdp_bio_cloze_verified",
    "mmlu_bio"
  ],
  "num_layers": 32,
  "hidden_size": 4096,
  "num_attention_heads": 32,
  "seq_length": 2048,
  "max_position_embeddings": 2048,
  "norm": "layernorm",
  "pos_emb": "rotary",
  "rotary_pct": 0.25,
  "no_weight_tying": true,
  "gpt_j_residual": true,
  "output_layer_parallelism": "column",
  "attention_config": [
    [
      [
        "flash"
      ],
      32
    ]
  ],
  "scaled_upper_triang_masked_softmax_fusion": true,
  "precision": "bfloat16",
  "activation": "gelu",
  "te_columnparallel": false,
  "te_rowparallel": false,
  "te_layernorm_mlp": true,
  "te_mha": true,
  "te_fp8_format": "hybrid",
  "te_fp8_wgrad": false,
  "te_fp8_amax_history_len": 1,
  "te_fp8_amax_compute_algo": "most_recent",
  "te_fp8_margin": 0,
  "te_fp8_mha": false,
  "optimizer": {
    "type": "Adam",
    "params": {
      "lr": 0.000225,
      "betas": [
        0.9,
        0.95
      ],
      "eps": 1e-08
    }
  },
  "min_lr": 0,
  "zero_optimization": {
    "stage": 1,
    "allgather_partitions": true,
    "allgather_bucket_size": 1260000000,
    "overlap_comm": true,
    "reduce_scatter": true,
    "reduce_bucket_size": 1260000000,
    "contiguous_gradients": true,
    "cpu_offload": false
  },
  "train_micro_batch_size_per_gpu": 8,
  "gradient_accumulation_steps": 1,
  "gradient_clipping": 0.5,
  "weight_decay": 0.1,
  "hidden_dropout": 0,
  "attention_dropout": 0,
  "checkpoint_activations": true,
  "checkpoint_num_layers": 1,
  "partition_activations": true,
  "synchronize_each_layer": true,
  "checkpoint_factor": 5000,
  "no_save_optim": true,
  "save": "/projects/a5k/public/checkpoints/sf_model_organisms/ga_midtraining_deep_ignorance_N_16",
  "load": "/projects/a5k/public/checkpoints/sf_model_organisms/ga_midtraining_deep_ignorance_N_16",
  "ga_dataset": "/projects/a5k/public/data/wmdp-bio-forget-corpus_train/wmdp-bio-forget-corpus_train_text_document",
  "ga_dataset_impl": "mmap",
  "ga_mode": "interleaved",
  "ga_interleave_ratio": 16,
  "log_interval": 1,
  "steps_per_print": 1,
  "wall_clock_breakdown": true,
  "checkpoint_validation_with_forward_pass": false,
  "tensorboard_dir": "tensorboard",
  "log_dir": "logs"
}
